site_name: 'ğŸ‡: `cfgs`: XDG standard config files ğŸ‡'

theme:
  name: material

  palette:
    primary:
      'red'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
